# just playing with GHA
name: integ-test

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      integ_tests_include:
        type: string
        description: |-
          List integration tests to include.
          Use "*" to run all tests.
          Use regex like 'test|^git_issue' to run only a subset.
        default: "*"
      integ_tests_exclude:
        type: string
        description: |-
          List integration tests to exclude.
        default: "^test_10|^test_11$"
      integ_seq_tests_include:
        type: string
        description: |-
          List seq integration tests to include.
        default: "^seq"
      integ_seq_tests_exclude:
        type: string
        description: |-
          List seq integration tests to exclude.
        default: "^seq2$"
      examples_include:
        type: string
        description: |-
          List examples to include into testing.
        default: "ex2,ex3"
      examples_exclude:
        type: string
        description: |-
          List examples to exclude into testing.
        default: "^bla$"
env:
  INTEG_TESTS_INCLUDE_SCHEDULE: "*"
  INTEG_TESTS_EXCLUDE_SCHEDULE: "^test_10|^test_11$"
  INTEG_SEQ_TESTS_INCLUDE_SCHEDULE: "seq"
  INTEG_SEQ_TESTS_EXCLUDE_SCHEDULE: "^seq2$"
  EXAMPLES_TESTS_INCLUDE_SCHEDULE: "*"
  EXAMPLES_TESTS_EXCLUDE_SCHEDULE: "^bla$"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  integration-prepare-env:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        sc_host:
          - https://10.5.11.200  # HC 9.1.x
    steps:
      - run: echo sc_host=$sc_host
    if: "${{ github.event.inputs.integ_tests_include || github.event.schedule }}"

  integ-matrix:
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:9
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - run: echo 'INTEG_TESTS_INCLUDE=${{ github.event.inputs.integ_tests_include || env.INTEG_TESTS_INCLUDE_SCHEDULE }}' >> $GITHUB_ENV
      - run: echo 'INTEG_TESTS_EXCLUDE=${{ github.event.inputs.integ_tests_exclude || env.INTEG_TESTS_EXCLUDE_SCHEDULE }}' >> $GITHUB_ENV
      - id: set-matrix
        shell: bash
        run: |-
          echo "matrix=$(
            echo -e "test1\ntest2\ntest3" |
            grep -v -E "${{ env.INTEG_TESTS_EXCLUDE }}" |
            grep -E "${{ env.INTEG_TESTS_INCLUDE }}" |
            jq -R -s -c 'split("\n")[:-1]'
          )" >> $GITHUB_OUTPUT
    if: "${{ github.event.inputs.integ_tests_include || github.event.schedule }}"

  integ-seq-matrix:
    needs:
      - integ-matrix
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:9
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - run: echo 'INTEG_SEQ_TESTS_INCLUDE=${{ github.event.inputs.integ_seq_tests_include || env.INTEG_SEQ_TESTS_INCLUDE_SCHEDULE }}' >> $GITHUB_ENV
      - run: echo 'INTEG_SEQ_TESTS_EXCLUDE=${{ github.event.inputs.integ_seq_tests_exclude || env.INTEG_SEQ_TESTS_EXCLUDE_SCHEDULE }}' >> $GITHUB_ENV
      - id: set-matrix
        shell: bash
        run: |-
          echo "matrix=$(
            echo -e "seq1\nseq2\nseq3\nseq4" |
            grep -v -E "${{ env.INTEG_SEQ_TESTS_EXCLUDE }}" |
            grep -E "${{ env.INTEG_SEQ_TESTS_INCLUDE }}" |
            jq -R -s -c 'split("\n")[:-1]'
          )" >> $GITHUB_OUTPUT
    if: "${{ github.event.inputs.integ_seq_tests_include || github.event.schedule }}"

  examples-matrix:
    needs:
      - integ-seq-matrix
    runs-on: [ubuntu-latest]
    container: quay.io/justinc1_github/scale_ci_integ:9
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - run: |
          if [ "" != "${{ github.event.schedule }}" ]
          then
            echo 'EXAMPLES_TESTS_INCLUDE=${{ env.EXAMPLES_TESTS_INCLUDE_SCHEDULE }}' >> $GITHUB_ENV
            echo 'EXAMPLES_TESTS_EXCLUDE=${{ env.EXAMPLES_TESTS_EXCLUDE_SCHEDULE }}' >> $GITHUB_ENV
          else
            echo 'EXAMPLES_TESTS_INCLUDE=${{ github.event.inputs.examples_include }}' >> $GITHUB_ENV
            echo 'EXAMPLES_TESTS_EXCLUDE=${{ github.event.inputs.examples_exclude }}' >> $GITHUB_ENV
          fi
      - id: set-matrix
        shell: bash
        run: |-
          echo "matrix=$(
            echo -e "ex1\nex2\nex3" |
            grep -v -E "${{ env.EXAMPLES_TESTS_EXCLUDE }}" |
            grep -E "${{ env.EXAMPLES_TESTS_INCLUDE }}" |
            jq -R -s -c 'split("\n")[:-1]'
          )" >> $GITHUB_OUTPUT
    if: "${{ github.event.inputs || github.event.schedule }}"

  integ-run:
    needs:
      - integ-matrix
    runs-on: [ubuntu-latest]
    # container: quay.io/justinc1_github/scale_ci_integ:9
    strategy:
      fail-fast: false
      matrix:
        test_name: ${{ fromJson(needs.integ-matrix.outputs.matrix) }}
        sc_host:
          - https://10.5.11.200
          - https://10.5.11.201
    steps:
      - run: echo matrix.sc_host=${{ matrix.sc_host }} matrix.test_name=${{ matrix.test_name }}
      - run: sleep 10
      - shell: bash
        run: |-
          if [ "${{ matrix.sc_host }} ${{ matrix.test_name }}" == "https://10.5.11.201 test1" ]
          then
            echo TTRT Exit with error
            exit 11
          else
            echo TTRT Continue
          fi

  integ-seq-run:
    needs:
      - integ-seq-matrix
      - integ-run
    if: "(!cancelled()) && (needs.integ-seq-matrix.result=='success')"
    runs-on: [ubuntu-latest]
    # container: quay.io/justinc1_github/scale_ci_integ:9
    strategy:
      fail-fast: false
      max-parallel: 2  # length of SC_HOSTs
      matrix:
        test_name: ${{ fromJson(needs.integ-seq-matrix.outputs.matrix) }}
        sc_host:
          - h200  # https://10.5.11.200
          - h201  # https://10.5.11.201

    concurrency:
      # we want at most 1 job per SC_HOST
      # we still allow to test multiple SC_HOSTs in parallel
      group: ${{ github.ref_name }}-{{ matrix.sc_host }}
      # will 2nd job be removed before run, or cancel the first job?
      cancel-in-progress: false

    steps:
      - run: date
      - run: echo matrix.sc_host=${{ matrix.sc_host }} matrix.test_name=${{ matrix.test_name }}
      - run: sleep 5
      - name: Checkout
        uses: actions/checkout@v4
      - shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          X_GITHUB_JOB_NAME: "integ-seq-run (${{ matrix.test_name }}, ${{ matrix.sc_host }})"
        run: |-
          if ! .github/job_retry_needed.py
          then
            echo SKIP test, job retry not needed
            exit 0
          fi

          if [ "${{ matrix.sc_host }} ${{ matrix.test_name }}" == "https://10.5.11.201 seq1" ]
          then
            echo TTRT Exit with error
            exit 11
          else
            echo TTRT Continue
          fi

  examples-run:
    needs:
      - examples-matrix
      - integ-seq-run
    if: "(!cancelled()) && (needs.examples-matrix.result=='success')"
    runs-on: [ubuntu-latest]
    # container: quay.io/justinc1_github/scale_ci_integ:9
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        example_name: ${{ fromJson(needs.examples-matrix.outputs.matrix) }}
    steps:
      - run: echo matrix.example_name=${{ matrix.example_name }}
      - run: sleep 10
      - name: Checkout
        uses: actions/checkout@v4
      - shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          X_GITHUB_JOB_NAME: "examples-run (${{ matrix.example_name }})"
        run: |-
          if ! .github/job_retry_needed.py
          then
            echo SKIP test, job retry not needed
            exit 0
          fi

          if [ "${{ matrix.test_name }}" == "ex3" ]
          then
            echo TTRT Exit with error
            exit 11
          else
            echo TTRT Continue
          fi
